# Generated by Django 5.0.4 on 2024-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
